name: Sensory Heaven Job

# Controls when the workflow will run
on:
  # Triggers the workflow on PRs
  pull_request:
    branches:
      - main

  # Triggers the workflow 3 am every Saturday
  # schedule:
  #   - cron: "0 3 * * 6"

env:
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }} # env_var: secrets.REPO_SECRETS
  EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }} # env_var: secrets.REPO_SECRETS
  FOURSQUARE_API_KEY: ${{ secrets.FOURSQUARE_API_KEY }} # env_var: secrets.REPO_SECRETS

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Set up Python
      uses: actions/setup-python@v4  # Use the latest version of setup-python
      with:
        python-version: '3.10.16'

    - name: Set environment variables # Don't have to store creds in streamlit
      run: |
        echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD  }}" >> $GITHUB_ENV
        echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME  }}" >> $GITHUB_ENV
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: List files in the repository (recursive)
      run: |
        ls -alR  # Lists all files to check the directory structure

    - name: Run app
      run: |
        python foursquare_app.py
